### ISSUE TITLE
Uncaught Error: Can't save buffer with no file path

### ISSUE THREAD

**Issue by tdjordan** [gogoprog/atom-gdb#11]
1. set breakpoint
2. hit F5

**Atom Version**: 1.0.11
**System**: Ubuntu 15.04
**Thrown From**: [atom-gdb](https://github.com/gogoprog/atom-gdb) package, v0.4.0
### Stack Trace

Uncaught Error: Can't save buffer with no file path

```
At /usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1011

Error: Can't save buffer with no file path
  at TextBuffer.module.exports.TextBuffer.saveAs (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1011:15)
  at TextBuffer.module.exports.TextBuffer.save (/usr/share/atom/resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1005:19)
  at TextEditor.module.exports.TextEditor.save (/usr/share/atom/resources/app.asar/src/text-editor.js:584:26)
  at Object.module.exports.AtomGdb.saveAll (/home/wr-linux/.atom/packages/atom-gdb/lib/atom-gdb.coffee:216:18)
  at Object.module.exports.AtomGdb.start (/home/wr-linux/.atom/packages/atom-gdb/lib/atom-gdb.coffee:94:6)
  at atom-workspace.subscriptions.add.atom.commands.add.atom-gdb:start (/home/wr-linux/.atom/packages/atom-gdb/lib/atom-gdb.coffee:31:82)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:245:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:524:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:347:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:184:20)

```
### Commands

```
     -0:00.5.0 atom-gdb:start (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {},
  "atom-gdb": {}
}
```
### Installed Packages

``` coffee
# User
atom-gdb, v0.4.0
docblockr, v0.7.3
sync-settings, v0.6.0

# Dev
No dev packages
```

**Comment by NuclearCookie** [comment]
This happens when you have a new file ( that has not been saved yet ) open in your editor, and the save on start option enabled.
