### ISSUE TITLE
Uncaught Error: spawn EACCES

### ISSUE THREAD

**Issue by TarekAloui** [gogoprog/atom-gdb#16]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Ubuntu 14.04.4
**Thrown From**: [atom-gdb](https://github.com/gogoprog/atom-gdb) package, v0.4.0
### Stack Trace

Uncaught Error: spawn EACCES

```
At /usr/share/atom/resources/app.asar/src/buffered-process.js:262

Error: spawn EACCES
    at exports._errnoException (util.js:856:11)
    at ChildProcess.spawn (internal/child_process.js:298:11)
    at Object.exports.spawn (child_process.js:374:9)
    at BufferedProcess.module.exports.BufferedProcess.spawn (/usr/share/atom/resources/app.asar/src/buffered-process.js:190:44)
    at new BufferedProcess (/usr/share/atom/resources/app.asar/src/buffered-process.js:52:14)
    at Object.module.exports.AtomGdb.runProcess (/home/tarek/.atom/packages/atom-gdb/lib/atom-gdb.coffee:67:24)
    at Object.module.exports.AtomGdb.startNoDebug (/home/tarek/.atom/packages/atom-gdb/lib/atom-gdb.coffee:125:6)
    at atom-workspace.subscriptions.add.atom.commands.add.atom-gdb:start-no-debug (/home/tarek/.atom/packages/atom-gdb/lib/atom-gdb.coffee:32:91)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:260:29)
    at CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:3:61)
    at CommandRegistry.module.exports.CommandRegistry.dispatch (/usr/share/atom/resources/app.asar/src/command-registry.js:160:19)
    at AtomEnvironment.module.exports.AtomEnvironment.dispatchApplicationMenuCommand (/usr/share/atom/resources/app.asar/src/atom-environment.js:1100:28)
    at EventEmitter.outerCallback (/usr/share/atom/resources/app.asar/src/application-delegate.js:327:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
```
### Commands

```
 25x -2:38.6.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:25.1.0 core:confirm (atom-text-editor.editor.mini.is-focused)
  4x -2:15.7.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -2:10.3.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:45.6.0 atom-gdb:start (ul.list-inline.tab-bar.inset-panel)
     -0:00.5.0 atom-gdb:start-no-debug (atom-text-editor.editor.power-mode.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-dark-ui",
      "material"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
activate-power-mode, v0.6.0
atom-gdb, v0.4.0
material, v2.2.0

# Dev
No dev packages
```

**Comment by gogoprog** [comment]
Added checks in a5c2bc168a2798e97f10ba5d79a5922e2cc72a4a
Should be fixed
